### ISSUE TITLE
Run tests to check running times of EDP

### ISSUE THREAD

**Issue by OlivierPMaas** [OlivierPMaas/TUD_Advanced-Algorithms_Prog#20]
- Compare with BestFirst on small (<=10) datasets.
- Compare with Greedy on datasets of size up to 60ish, maybe 75ish. See what works.
- Obviously, find a way to check running times in Java :P but also save these in a nice array/matrix.

**Comment by JohannaKorte** [comment]
Managed to get all running times in microseconds. Still need a way to represent these running times times though, preferably in a graph. Since I don't know what the TF and RDD values mean, I'm unsure of taking the average running time per size and comparing those
