### ISSUE TITLE
Report: Note how we deal with multiple jobs sharing a processing time

### ISSUE THREAD

**Issue by OlivierPMaas** [OlivierPMaas/TUD_Advanced-Algorithms_Prog#21]
From these jobs we take the job with highest position in the linked list and remove it from the schedule; the others stay.

See the findK()-function in Schedule.

**Comment by JohannaKorte** [comment]
Because of the many different functions that we have, i was not able to implement the findK function, and thus the handling of multiple jobs sharing a processing time within the pseudocode. So we will have to mention this explicitly in the report

**Comment by OlivierPMaas** [comment]
I would imagine that most Schedule-functions do not have to be mentioned in the pseudocode to begin with; we can assume that their titles elucidate their function, and coding them based on that information is trivial. Probably the important thing to write in pseudocode is our algorithm itself. :)
